// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/11/2024, 9:15:37 PM
const configMerger = require("C:/Users/micha/portfolio/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/micha/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/micha/portfolio/composables/**/*.{js,ts,mjs}","C:/Users/micha/portfolio/utils/**/*.{js,ts,mjs}","C:/Users/micha/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/micha/portfolio/app.config.{js,ts,mjs}"] } }));

module.exports = (() => {const cfg=config;cfg["content"]["files"]["11"] = "C:/Users/micha/portfolio/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})()
